{
 "title": "Operator Metrics",
 "tags": [
  "kubernetes-operator",
  "neonkube-operator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_interval", "label": "min_interval", "query": "5s,15s,1m,2m,5m,15m" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(operator_version_info, namespace)"
    }
   },
   {
    "name": "operator",
    "label": "operator",
    "query": {
     "query": "label_values(operator_version_info{namespace=~\"$namespace\"}, operator)"
    }
   },
   {
    "name": "controller",
    "label": "controller",
    "query": {
     "query": "label_values(operator_eventqueue_queue_duration_seconds_sum{namespace=~\"$namespace\", operator=~\"$operator\"}, controller)"
    }
   },
   {
    "name": "webhook",
    "label": "webhook",
    "query": {
     "query": "label_values(operator_webhook_requests_total{namespace=~\"$namespace\", operator=~\"$operator\"}, webhook)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(operator_version_info{namespace=~\"$namespace\", operator=~\"$operator\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reconciliation Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Reconciliation Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(operator_controller_reconcile_total{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Error Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(operator_controller_reconcile_errors_total{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(operator_eventqueue_queue_duration_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P50 {{controller}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(operator_eventqueue_queue_duration_seconds_bucket{operator=\"$operator\", namespace=\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P90 {{controller}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(operator_eventqueue_queue_duration_seconds_bucket{operator=\"$operator\", namespace=\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P99 {{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(operator_eventqueue_adds_total{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(operator_eventqueue_work_duration_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P50 {{controller}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(operator_eventqueue_work_duration_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P90 {{controller}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(operator_eventqueue_work_duration_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller, le))",
     "legendFormat": "P99 {{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(operator_eventqueue_retries_total{operator=~\"$operator\", namespace=~\"$namespace\", controller=~\"$controller\"}[$__rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Webhook Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Webhook Latency (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing a webhook takes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(operator_webhook_latency_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", webhook=~\"$webhook\"}[$__rate_interval])) by (webhook, le))",
     "legendFormat": "P50 {{webhook}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(operator_webhook_latency_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", webhook=~\"$webhook\"}[$__rate_interval])) by (webhook, le))",
     "legendFormat": "P90 {{webhook}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(operator_webhook_latency_seconds_bucket{operator=~\"$operator\", namespace=~\"$namespace\", webhook=~\"$webhook\"}[$__rate_interval])) by (webhook, le))",
     "legendFormat": "P99 {{webhook}}"
    }
   ]
  },
  {
   "title": "Webhook Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(operator_webhook_requests_total{operator=~\"$operator\", namespace=~\"$namespace\", webhook=~\"$webhook\"}[$__rate_interval])) by (webhook)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}